### PR TITLE
Update schema definitions

### PR DESCRIPTION
**Pull request by jjleigh**
*Issue #, if available:*

*Description of changes:*
**Read me update:**
- Added a note to state that an account must have a CloudTrail for MoveAccount events to be detected by event bus.

**Schema updates:**
- Update link data pattern to support underscores
- Extend the inlinePolicyDocument schema for permission set create. Added required fields and schemas for Action, Resource and Effect

tested new schema using
https://www.jsonschemavalidator.net/

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tamara-h** [comment]
Hi @jjleigh thanks for this PR, it all looks ok from my side to begin with - can you confirm that you've deployed these changes in your sandbox account and that it operates as expected?

**Comment by jjleigh** [comment]
> Hi @jjleigh thanks for this PR, it all looks ok from my side to begin with - can you confirm that you've deployed these changes in your sandbox account and that it operates as expected?

Hi, I tested the changes to the link data pattern but did not test the other change in the sandbox only in the schema validator. I will do that and confirm.

**Comment by jjleigh** [comment]
@tamara-h I was able to test and everything is working. I had to remove a few final commas. Does the version need to be updated somewhere?

**Review by tamara-h — APPROVED** [review]
Fab LGTM, thanks for contributing 😄

**Pull request merged**
